# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: appDir
  value: verify-app

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '2.6'

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'
  workingDirectory: $(appDir)

- script: rails db:migrate RAILS_ENV=test
  displayName: 'rails db:migrate'
  workingDirectory: $(appDir)

- script: bundle exec rake
  displayName: 'bundle exec rake'
  workingDirectory: $(appDir)

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'WheelerLearning/wheeler146'
    appName: 'wheeler-verify-app-site'
    deploymentMethod: 'zipDeploy'
    package: $(System.DefaultWorkingDirectory)/$(appDir)
    slotName: 'stg'
