# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals wheeler-verify-app-agent

variables:
- name: appDir
  value: app

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '14.16.1'
  displayName: 'Install Node'
  
- script: |
    npm install --global yarn
    yarn --version
  displayName: 'Install Yarn'
  workingDirectory: $(appDir)
  
- script: bundle install
  displayName: 'Install Bundle Dependencies'
  workingDirectory: $(appDir)

- script: yarn install --check-files
  displayName: 'Install Yarn Dependencies'
  workingDirectory: $(appDir)
  
- script: |
    rm -rf bin/webpack*
    rails webpacker:install
  displayName: 'Install Webpacker Dependencies'
  workingDirectory: $(appDir)

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'WheelerLearning/wheeler146'
    appName: 'wheeler-verify-app-site'
    deploymentMethod: 'zipDeploy'
    package: $(System.DefaultWorkingDirectory)/$(appDir)
    slotName: 'stg'
