# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'
    
- displayName: 'gem install rails'
  script: gem install rails && rails -v
  
- displayName: 'bundle install'
  script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  
- displayName: 'bundle exec rake'
  script: bundle exec rake
  
- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Azure service connection>'
    appName: '<name of web app>'
    slotName: staging
  
