# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals wheeler-verify-app-agent

variables:
- name: appDir
  value: verify-app

steps:
- script: |
    sudo apt-get update
    sudo apt-get install autoconf
    sudo apt-get install bison
    sudo apt-get install build-essential
    sudo apt-get install curl
    sudo apt-get install git
    sudo apt-get install libffi-dev
    sudo apt-get install libgdbm-dev
    sudo apt-get install libncurses5-dev
    sudo apt-get install libreadline-dev
    sudo apt-get install libssl-dev
    sudo apt-get install libyaml-dev
    sudo apt-get install zlib1g-dev
  displayName: 'install dependencies'
  workingDirectory: $(appDir)
  
- script: |
    # get installer and run installer
    curl -sL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash -

    # check for rbenv in path
    grep -q rbenv ~/.bashrc
    if [[ $? -eq 1 ]]; then

        # update path
        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(rbenv init -)"' >> ~/.bashrc
        source ~/.bashrc
    fi
    rbenv -v
  displayName: 'install rbenv'
  workingDirectory: $(appDir)
  
- script: |
    rbenv install 2.6.2
    rbenv global 2.6.2
    ruby -v
  displayName: 'install ruby'
  workingDirectory: $(appDir)

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'install bundler'
  workingDirectory: $(appDir)

- script: rails db:migrate RAILS_ENV=test
  displayName: 'rails db:migrate'
  workingDirectory: $(appDir)

- script: bundle exec rake
  displayName: 'bundle exec rake'
  workingDirectory: $(appDir)

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'WheelerLearning/wheeler146'
    appName: 'wheeler-verify-app-site'
    deploymentMethod: 'zipDeploy'
    package: $(System.DefaultWorkingDirectory)/$(appDir)
    slotName: 'stg'
