# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals wheeler-verify-app-agent

variables:
- name: appDir
  value: verify-app

steps:
- script: |
    sudo apt update
    sudo apt install autoconf
    sudo apt install bison
    sudo apt install build-essential
    sudo apt install curl
    sudo apt install git
    sudo apt install libffi-dev
    sudo apt install libgdbm-dev
    sudo apt install libncurses5-dev
    sudo apt install libreadline-dev
    sudo apt install libssl-dev
    sudo apt install libyaml-dev
    sudo apt install zlib1g-dev
  displayName: 'install dependencies'
  workingDirectory: $(appDir)
  
- script: |
    curl -sL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash -
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(rbenv init -)"' >> ~/.bashrc
    source ~/.bashrc
  displayName: 'install rbenv'
  workingDirectory: $(appDir)
  
- script: |
    rbenv install 2.6.2
    rbenv global 2.6.2
    ruby -v
  displayName: 'install ruby'
  workingDirectory: $(appDir)

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'install bundler'
  workingDirectory: $(appDir)

- script: rails db:migrate RAILS_ENV=test
  displayName: 'rails db:migrate'
  workingDirectory: $(appDir)

- script: bundle exec rake
  displayName: 'bundle exec rake'
  workingDirectory: $(appDir)

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'WheelerLearning/wheeler146'
    appName: 'wheeler-verify-app-site'
    deploymentMethod: 'zipDeploy'
    package: $(System.DefaultWorkingDirectory)/$(appDir)
    slotName: 'stg'
