# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '2.7'
    
#- script: |
#    gem install rails
#    rails -v
#  displayName: 'gem install rails'
#  workingDirectory: verify-app

- script: |
    gem install bundler
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'
  workingDirectory: verify-app

- script: bundle exec rake
  displayName: 'bundle exec rake'
  workingDirectory: verify-app

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'WheelerLearning/wheeler146'
    appName: 'wheeler-verify-app-site'
    slotName: 'stg'
