development:
  clients:
    default:
      uri: "<%= ENV['MONGODB_URI'] %>"
      options:
        connect_timeout: 15
  sessions:
    default:
      options:
        ssl: true

test:
  clients:
    default:
      database: verify-test 
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
