development:
  clients:
    default:
      # uri: "<%= ENV['MONGODB_URI'] %>"
      uri: mongodb://wheeler-verify-app-mongo-db:H428BszKFgZXSvcJv2y1ye03MTgsZPDL2a2eeP23k85hy015OvZ5MWMFfD211FTnHkK3ssdwEAKEjIdIZdTkug==@wheeler-verify-app-mongo-db.mongo.cosmos.azure.com:10255/main?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@wheeler-verify-app-mongo-db@
      options:
        connect_timeout: 15
  sessions:
    default:
      options:
        ssl: true

test:
  clients:
    default:
      database: verify-test 
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
