development:
  clients:
    default:
      database: verify-development
      hosts:
        - localhost:27017
      options:

test:
  clients:
    default:
      database: verify-test 
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
